# yaml plugin metadata

name: Git repository retriever
version: 2.1.0
rundeckPluginVersion: 1.1
author: The National Library of Finland
date: 2016-08-14
providers:
  - name: Git repository retriever
    description: Retrieve a Git repository via SSH
    service: WorkflowStep
    plugin-type: script
    script-interpreter: /usr/bin/python
    script-file: plugin.py
    script-args:
    config:
      - name: repository-url
        title: Repository URL
        type: String
        required: true
        description: The URL of the Git repository
      - name: checkout-reference
        title: Checkout reference
        type: String
        required: true
        default: master
        description: Git reference that is passed to 'git checkout'. Defaults to 'master'
      - name: allowed-branch
        title: Allowed branch
        type: String
        required: false
        description: Only allow commits that exist in this branch
      - name: target-directory
        title: Target directory path
        type: String
        required: true
        description: Path of the target directory where the checked-out source code will be copied to
      - name: disable-hostkey-verification
        title: Disable host key verification
        type: Boolean
        default: false
